package surrealdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"github.com/surrealdb/surrealdb.go"
	sdkModels "github.com/surrealdb/surrealdb.go/pkg/models"

	TypesM "github.com/dailaim/surrealdb-gorm/types"
)

type DriverResult struct {
	Rows int64
}

func (DriverResult) LastInsertId() (int64, error) {
	return 0, nil
}

func (d DriverResult) RowsAffected() (int64, error) {
	return d.Rows, nil
}

func (dialector *Dialector) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	// Intercept INSERT INTO <edge_table> generated by GORM's many2many association handler.
	upperQuery := strings.ToUpper(strings.TrimSpace(query))
	if strings.HasPrefix(upperQuery, "INSERT INTO") {
		rest := strings.TrimSpace(query[len("INSERT INTO"):])
		tbl := strings.FieldsFunc(rest, func(r rune) bool {
			return r == ' ' || r == '(' || r == '`' || r == '"'
		})
		if len(tbl) > 0 {
			if registeredName, ok := dialector.FindEdgeTable(tbl[0]); ok {
				if len(args) >= 2 {
					inID := extractRecordID(args[0])
					outID := extractRecordID(args[1])
					if inID != nil && outID != nil {
						rel := &surrealdb.Relationship{
							In:       *inID,
							Out:      *outID,
							Relation: sdkModels.Table(registeredName),
						}
						if _, err := surrealdb.InsertRelation[interface{}](ctx, dialector.Conn, rel); err != nil {
							return nil, err
						}
						return DriverResult{Rows: 1}, nil
					}
				}
			}
		}
	}

	// Sanitize UPDATE SQL (Remove ID from SET)
	if len(query) > 6 && strings.HasPrefix(strings.ToUpper(query), "UPDATE") {
		lowerSql := strings.ToLower(query)
		setIdx := strings.Index(lowerSql, " set ")
		whereIdx := strings.LastIndex(lowerSql, " where ")
		if setIdx != -1 && (whereIdx == -1 || setIdx < whereIdx) {
			beforeSet := query[:setIdx+5]
			var setPart, afterSet string
			if whereIdx != -1 {
				setPart = query[setIdx+5 : whereIdx]
				afterSet = query[whereIdx:]
			} else {
				setPart = query[setIdx+5:]
			}
			parts := strings.Split(setPart, ",")
			var cleanParts []string
			for _, p := range parts {
				trimmed := strings.TrimSpace(p)
				if strings.HasPrefix(trimmed, "`id` =") || strings.HasPrefix(trimmed, "id =") || strings.HasPrefix(trimmed, "\"id\" =") {
					continue
				}
				cleanParts = append(cleanParts, p)
			}
			newSetPart := strings.Join(cleanParts, ", ")
			query = beforeSet + newSetPart + " " + afterSet
		}
	}

	// Translate standard SQL DELETE FROM to SurrealQL DELETE
	if len(query) > 12 && strings.HasPrefix(strings.ToUpper(strings.TrimSpace(query)), "DELETE FROM ") {
		idx := strings.Index(strings.ToUpper(query), "DELETE FROM ")
		if idx != -1 {
			query = query[:idx] + "DELETE " + strings.TrimSpace(query[idx+12:])
		}
	}

	// Map args to map[string]interface{}
	params := make(map[string]interface{})
	for i, v := range args {
		if m, ok := v.(json.Marshaler); ok {
			if b, err := m.MarshalJSON(); err == nil {
				var iv interface{}
				if err := json.Unmarshal(b, &iv); err == nil {
					params[fmt.Sprintf("p%d", i+1)] = iv
					continue
				}
			}
		}
		params[fmt.Sprintf("p%d", i+1)] = v
	}

	results, err := surrealdb.Query[interface{}](ctx, dialector.Conn, query, params)
	if err != nil {
		return nil, err
	}

	var count int64
	if len(*results) > 0 {
		res := (*results)[0]
		if res.Status != "OK" {
			return nil, fmt.Errorf("surrealdb exec error: %v", res)
		}
		if res.Result != nil {
			val := reflect.ValueOf(res.Result)
			if val.Kind() == reflect.Slice || val.Kind() == reflect.Array {
				count = int64(val.Len())
			} else {
				count = 1
			}
		}
	}

	return DriverResult{Rows: count}, nil
}

// extractRecordID coerces an interface{} arg value into a *sdkModels.RecordID.
func extractRecordID(v interface{}) *sdkModels.RecordID {
	if v == nil {
		return nil
	}
	rv := reflect.ValueOf(v)
	for rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface {
		if rv.IsNil() {
			return nil
		}
		rv = rv.Elem()
	}
	concrete := rv.Interface()
	switch id := concrete.(type) {
	case sdkModels.RecordID:
		return &id
	case TypesM.RecordID:
		native := id.RecordID
		return &native
	}
	b, err := json.Marshal(concrete)
	if err != nil {
		return nil
	}
	var rid sdkModels.RecordID
	if err := json.Unmarshal(b, &rid); err != nil {
		return nil
	}
	return &rid
}
